title: News Classification Project
description: A machine learning project for news article classification
theme: jekyll-theme-cayman

# Add notebook display support
plugins:
  - jekyll-jupyter-notebook
baseurl: ""
include: [src/]
url: "https://praykar.github.io/newsclassifier"
author:
  name: "Prakhar Kulshrestha"
  email: "praykar@live.com"
social:
  github: "praykar"
