theme: minima
title: My Project Page
description: A showcase of Business Case project work
baseurl: ""
url: "https://praykar.github.io/newsclassifier"
author:
  name: "Prakhar Kulshrestha"
  email: "praykar@live.com"
social:
  github: "praykar"
